game_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('games/', include('games.urls')),
    path('admin/', admin.site.urls),
]

games/urls.py
from django.urls import path

from . import views

app_name = 'game'

urlpatterns = [
    # ex: /games/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /games/5/details
    path('<int:pk>/details', views.DetailView.as_view(), name='detail'),
    # ex: /games/5/favourite
    path('<int:genre_id>/favourite', views.favourite, name='favourite'),
]

games/models.py
from django.db import models


class Genre(models.Model):
    title = models.CharField(max_length=200)
    total_games = models.FloatField(default=0)

    def __str__(self):
        return f'{self.title}. Total Games: {self.total_games}'


class Game(models.Model):
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    developer_name = models.CharField(max_length=200)
    game_logo = models.CharField(max_length=1000)
    game_size = models.FloatField(default=0)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.title} created by developer {self.developer_name}'

games/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Genre, Game


class IndexView(generic.ListView):
    context_object_name = 'latest_genres'
    template_name = 'games/index.html'

    def get_queryset(self):
        return Genre.objects.all()


class DetailView(generic.DetailView):
    model = Genre
    template_name = 'games/detail.html'


def favourite(request, genre_id):
    genre = get_object_or_404(Genre, pk=genre_id)
    try:
        game = genre.game_set.get(pk=request.POST['game'])
    except (KeyError, Game.DoesNotExist):
        return render(request, 'games/detail.html', {
            'genre': genre,
            'error_message': 'Incorrect game selected'
        })
    else:
        game.is_favorite = True
        game.save()
        return HttpResponseRedirect(reverse('game:detail', args=(genre.id,)))

games/templates/games/detail.html
<h1>Genre: {{ genre.title }}</h1>

<h3>Following are the games for this genre. (Total: {{ genre.game_set.count }} games)</h3>

{% if error_message %}
    <p style="color: red"><strong> {{ error_message }} </strong></p>
{% endif %}

<form action="{% url 'game:favourite' genre.id %}" method="post">
    {% csrf_token %}
    {% for game in genre.game_set.all %}
        <input type="radio" id="game{{ forloop.counter }}" name="game" value="{{ game.id }}" />
        <label for="game{{ forloop.counter }}"> 
            {{ game.title }}
            {% if game.is_favorite %}
                <img src="http://tiny.cc/kmlqaz" width="20" height="20"/>
            {% endif %}
        </label><br>
    {% endfor %}

    <input type="submit" value="Favourite">
</form>

games/templates/games/index.html
<h1> Genres for Games </h1>
{% if latest_genres %}
    <ul>
        {% for genre in latest_genres %}
            <li><a href="{% url 'game:detail' genre.id %}">{{ genre }}</a></li>
        {% endfor %}
    </ul>

{% else %}
    <h2> There are no genres in the DataBase </h2>
{% endif %}